# https://pre-commit.com/
ci:
    autofix_commit_msg: 'ci: auto fixes from pre-commit.com hooks'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'

# prepare-commit-msg is used by hook id: check-message
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
