- name: Set up local development environment
  hosts: local
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - {role: package_manager, tags: ['package_manager']}
    - {role: common}
    - {role: devbox}
    - {role: fzf, tags: ['fzf']}
    - {role: git, tags: ['git']}
    - {role: k9s, tags: ['k9s']}
    # - {role: rg, tags: ['rg']}
