- name: Install fzf
  apt:
    name: fzf
    state: present
  become: true
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution in ["Debian", "Ubuntu"]  # Ensures APT is used on Debian-based systems
  tags:
    - fzf
