- name: Install fzf with Homebrew
  homebrew: name=fzf state=present
  when: ansible_os_family == "Darwin"

- name: Install fzf with APT
  apt: name=fzf state=present
  when: ansible_os_familly == "Debian"
