
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Check if .zshrc exists
  stat:
    path: "{{ dotfiles_user_home }}/.zshrc"
  register: zshrc_exists

- name: Copy aliases.zsh if .zshrc does not exist
  copy:
    src: aliases.zsh
    dest: "{{ dotfiles_user_home }}/.zshrc"
  when: not zshrc_exists.stat.exists
