
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: source aliases.zsh
  copy: src=aliases.zsh dest={{dotfiles_user_home}}/.zshrc
  when: not exists({{dotfiles_user_home}}/.zshrc)
