# add more package base on your requirement
# gcc, make are used by pyenv to compile python code.  
- name: Install common packages
  apt:
    name:
      - curl
      - direnv
      - gcc
      - make
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install dependencies for Python build
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
    state: present
  become: true
  tags: 
    - python
  when: ansible_os_family == "Debian"

- name: Install Homebrew for Linux
  shell: echo '\n' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: ansible_os_family in ['Debian', 'RedHat']
